import { useMemo, useState } from 'react'
import './App.css'

type View = 'discover' | 'restaurant' | 'rankings' | 'jobs'
type Role = 'Customer' | 'Employee' | 'Manager'
type Restaurant = { id: number; name: string; cuisine: string; area: string; rating: number; reviews: number; employees: number; jobs: number; image: string }
type Employee = { rank: number; movement: string; name: string; role: string; place: string; rating: number; count: number; badge: string; initials: string }

const restaurants: Restaurant[] = [
  { id: 1, name: 'Mziuri Kitchen', cuisine: 'Georgian', area: 'Vera, Tbilisi', rating: 4.8, reviews: 328, employees: 18, jobs: 3, image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85' },
  { id: 2, name: 'Riviera Table', cuisine: 'Mediterranean', area: 'Vake, Tbilisi', rating: 4.7, reviews: 241, employees: 12, jobs: 2, image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=85' },
  { id: 3, name: 'Kura Social Club', cuisine: 'Modern European', area: 'Old Town, Tbilisi', rating: 4.6, reviews: 189, employees: 24, jobs: 5, image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=85' },
]
const employees: Employee[] = [
  { rank: 1, movement: '+2', name: 'Nino Beridze', role: 'Head Waiter', place: 'Mziuri Kitchen', rating: 4.96, count: 243, badge: 'Customer Favorite', initials: 'NB' },
  { rank: 2, movement: '−1', name: 'Giorgi Kapanadze', role: 'Sous Chef', place: 'Kura Social Club', rating: 4.93, count: 198, badge: 'Top Performer', initials: 'GK' },
  { rank: 3, movement: '—', name: 'Mariam Chikovani', role: 'Bartender', place: 'Riviera Table', rating: 4.91, count: 175, badge: 'Team Player', initials: 'MC' },
  { rank: 4, movement: '+4', name: 'Luka Maisuradze', role: 'Server', place: 'Mziuri Kitchen', rating: 4.89, count: 154, badge: 'Rising Star', initials: 'LM' },
]
const jobs = [
  { title: 'Senior Waiter', place: 'Mziuri Kitchen', type: 'Full-time', salary: '1,800–2,200 GEL', area: 'Vera, Tbilisi' },
  { title: 'Pastry Chef', place: 'Riviera Table', type: 'Full-time', salary: '2,400–3,000 GEL', area: 'Vake, Tbilisi' },
  { title: 'Bartender', place: 'Kura Social Club', type: 'Part-time', salary: '1,200–1,600 GEL', area: 'Old Town, Tbilisi' },
]

function App() {
  const [view, setView] = useState<View>('discover')
  const [selected, setSelected] = useState(restaurants[0])
  const [tab, setTab] = useState('Overview')
  const [query, setQuery] = useState('')
  const [location, setLocation] = useState('Tbilisi')
  const [modal, setModal] = useState<'login' | 'register' | null>(null)
  const [role, setRole] = useState<Role>('Customer')
  const filtered = useMemo(() => restaurants.filter((r) => `${r.name} ${r.cuisine} ${r.area}`.toLowerCase().includes(query.toLowerCase())), [query])
  const openRestaurant = (restaurant: Restaurant) => { setSelected(restaurant); setTab('Overview'); setView('restaurant') }
  const openAuth = (mode: 'login' | 'register') => setModal(mode)

  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={() => setView('discover')}><span className="brand-mark">F</span><span>floorstaff</span></button><nav className="main-nav"><button className={view === 'discover' || view === 'restaurant' ? 'active' : ''} onClick={() => setView('discover')}>Restaurants</button><button className={view === 'jobs' ? 'active' : ''} onClick={() => setView('jobs')}>Jobs</button><button className={view === 'rankings' ? 'active' : ''} onClick={() => setView('rankings')}>Rankings</button><button onClick={() => openAuth('register')}>How it works</button></nav><div className="top-actions"><button className="location-pill" onClick={() => setLocation(location === 'Tbilisi' ? 'Batumi' : 'Tbilisi')}>⌖ {location}</button><button className="avatar" onClick={() => openAuth('login')}>JD</button></div></header>
    <main>{view === 'discover' && <Discover query={query} setQuery={setQuery} list={filtered} openRestaurant={openRestaurant} setView={setView} />}{view === 'restaurant' && <RestaurantDetail restaurant={selected} tab={tab} setTab={setTab} openAuth={openAuth} />}{view === 'rankings' && <Rankings openAuth={openAuth} />}{view === 'jobs' && <Jobs />}</main>
    <footer><strong>floorstaff</strong><span>Restaurants are more than food. They’re the people inside them.</span><span>© 2026</span></footer>{modal && <AuthModal mode={modal} role={role} setRole={setRole} close={() => setModal(null)} />}
  </div>
}

function Discover({ query, setQuery, list, openRestaurant, setView }: { query: string; setQuery: (v: string) => void; list: Restaurant[]; openRestaurant: (r: Restaurant) => void; setView: (v: View) => void }) {
  return <div className="page discover-page"><section className="welcome-row"><div><p className="eyebrow">MONDAY, SEPTEMBER 7 · YOUR CITY GUIDE</p><h1>Good places.<br /><em>Great people.</em></h1><p className="intro">Discover the restaurants, teams, and opportunities shaping hospitality in Tbilisi.</p></div><button className="location-card"><span className="pin">⌖</span><span><small>YOUR LOCATION</small><strong>Tbilisi, Georgia</strong></span><span>⌄</span></button></section><section className="search-row"><div className="search-box"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search restaurants, cuisines, or people" /><kbd>⌘ K</kbd></div><button className="filter-button">☷ <span>Filters</span></button><button className="primary-button" onClick={() => setView('jobs')}>Browse jobs <span>↗</span></button></section><section className="section-heading"><div><p className="eyebrow">CURATED FOR YOU</p><h2>Restaurants near Tbilisi</h2></div><button className="text-button">View map <span>↗</span></button></section><section className="restaurant-grid">{list.map((restaurant) => <RestaurantCard key={restaurant.id} restaurant={restaurant} onClick={() => openRestaurant(restaurant)} />)}</section><section className="split-section"><div><div className="section-heading"><div><p className="eyebrow">THE PEOPLE BEHIND THE PLATES</p><h2>Rising in your city</h2></div><button className="text-button" onClick={() => setView('rankings')}>See rankings <span>↗</span></button></div><div className="mini-ranking">{employees.slice(0, 3).map((employee) => <RankingRow key={employee.rank} employee={employee} compact />)}</div></div><div className="opportunity-card"><p className="eyebrow">FOR HOSPITALITY PROFESSIONALS</p><h2>Your work deserves a reputation.</h2><p>Build a profile that follows your career, celebrate the feedback that matters, and find your next great team.</p><button className="dark-button" onClick={() => setView('rankings')}>Explore the community <span>→</span></button></div></section></div>
}
function RestaurantCard({ restaurant, onClick }: { restaurant: Restaurant; onClick: () => void }) { return <button className="restaurant-card" onClick={onClick}><div className="restaurant-image" style={{ backgroundImage: `url(${restaurant.image})` }}><span className="open-label"><i /> Open now</span><span className="save-button">♡</span></div><div className="restaurant-content"><div className="card-title-row"><h3>{restaurant.name}</h3><strong>★ {restaurant.rating}</strong></div><p>{restaurant.cuisine} · {restaurant.area}</p><div className="card-meta"><span>{restaurant.reviews} reviews</span><span>{restaurant.employees} people</span><span>{restaurant.jobs} jobs</span></div></div></button> }
function RestaurantDetail({ restaurant, tab, setTab, openAuth }: { restaurant: Restaurant; tab: string; setTab: (v: string) => void; openAuth: (mode: 'login' | 'register') => void }) { return <div className="page detail-page"><button className="back-button" onClick={() => setTab('Overview')}>← Back to restaurants</button><div className="detail-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(20,25,25,.86), rgba(20,25,25,.1)), url(${restaurant.image})` }}><div><span className="verified">✓ Verified restaurant</span><h1>{restaurant.name}</h1><p>{restaurant.cuisine} · {restaurant.area} · $$</p></div><div className="hero-rating"><strong>{restaurant.rating}</strong><span>★ ★ ★ ★ ★</span><small>{restaurant.reviews} guest ratings</small></div></div><div className="tabs">{['Overview', 'Employees', 'Reviews', 'Jobs', 'Ratings'].map((item) => <button className={tab === item ? 'active' : ''} key={item} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === 'Overview' ? <div className="detail-grid"><section><p className="detail-copy">A warm neighborhood table where Georgian tradition meets a bright, contemporary room. Mziuri Kitchen is known for generous hospitality, open-fire cooking, and a team that remembers your name.</p><div className="stat-strip"><div><strong>4.8</strong><span>Restaurant rating</span></div><div><strong>{restaurant.employees}</strong><span>Team members</span></div><div><strong>{restaurant.jobs}</strong><span>Open positions</span></div></div><h2>Meet the team</h2><div className="employee-grid">{employees.slice(0, 3).map((employee) => <EmployeeCard key={employee.rank} employee={employee} openAuth={openAuth} />)}</div></section><aside><div className="info-panel"><p className="eyebrow">GOOD TO KNOW</p><div><span>⌖</span><strong>{restaurant.area}</strong><small>12 minutes from your location</small></div><div><span>◷</span><strong>12:00 – 00:00</strong><small>Open today</small></div><div><span>◎</span><strong>Georgian · $$</strong><small>Menu and wine bar</small></div></div><div className="manager-panel"><p className="eyebrow">TEAM HEALTH</p><h3>Manager rating</h3><div className="manager-score"><strong>4.6</strong><span>★★★★★</span></div><p>Based on 42 anonymous employee ratings</p><button onClick={() => openAuth('login')}>View workplace feedback →</button></div></aside></div> : <div className="placeholder-panel"><span className="panel-icon">✦</span><h2>{tab} for {restaurant.name}</h2><p>Sign in to interact with reviews, jobs, and team ratings.</p><button className="primary-button" onClick={() => openAuth('login')}>Sign in to continue</button></div>}</div> }
function EmployeeCard({ employee, openAuth }: { employee: Employee; openAuth: (mode: 'login' | 'register') => void }) { return <button className="employee-card" onClick={() => openAuth('login')}><div className="initials">{employee.initials}</div><div className="employee-info"><h3>{employee.name}</h3><p>{employee.role}</p><div><span>★ {employee.rating}</span><small>{employee.count} ratings</small></div></div><span className="employee-arrow">↗</span></button> }
function Rankings({ openAuth }: { openAuth: (mode: 'login' | 'register') => void }) { return <div className="page rankings-page"><div className="page-intro"><p className="eyebrow">THE REPUTATION BOARD</p><h1>Restaurant rankings</h1><p>Confidence-weighted ratings from customers and coworkers. A proven track record matters more than a tiny sample size.</p></div><div className="ranking-controls"><button className="selected">City · Tbilisi</button><button>Country · Georgia</button><button>All roles</button><span>Updated 8 min ago</span></div><div className="ranking-table"><div className="table-head"><span>RANK</span><span>EMPLOYEE</span><span>RESTAURANT</span><span>RATING</span><span>RATINGS</span></div>{employees.map((employee) => <RankingRow key={employee.rank} employee={employee} openAuth={openAuth} />)}</div></div> }
function RankingRow({ employee, compact = false, openAuth }: { employee: Employee; compact?: boolean; openAuth?: (mode: 'login' | 'register') => void }) { return <button className={`ranking-row ${compact ? 'compact' : ''}`} onClick={() => openAuth?.('login')}><span className="rank-number">{employee.rank}</span><span className={`movement ${employee.movement.startsWith('+') ? 'up' : employee.movement.startsWith('−') ? 'down' : ''}`}>{employee.movement}</span><span className="ranking-person"><span className="initials small">{employee.initials}</span><span><strong>{employee.name}</strong><small>{employee.role}</small></span></span>{!compact && <span className="restaurant-name">{employee.place}</span>}<span className="ranking-score">★ {employee.rating.toFixed(2)}<small>{employee.badge}</small></span>{!compact && <span className="rating-count">{employee.count}</span>}</button> }
function Jobs() { return <div className="page jobs-page"><div className="page-intro"><p className="eyebrow">OPPORTUNITIES NEAR YOU</p><h1>Find your next table.</h1><p>Open roles at restaurants where the people and culture are worth showing up for.</p></div><div className="jobs-layout"><div className="job-filters"><strong>Filter roles</strong><label>Location<select><option>Tbilisi, Georgia</option><option>Batumi, Georgia</option></select></label><label>Employment type<select><option>All types</option><option>Full-time</option><option>Part-time</option></select></label><label>Role<select><option>All roles</option><option>Waiter</option><option>Chef</option><option>Bartender</option></select></label></div><div className="job-list">{jobs.map((job) => <article className="job-card" key={job.title}><div className="job-logo">{job.place[0]}</div><div className="job-body"><div className="job-topline"><span>{job.type}</span><small>Posted 2 days ago</small></div><h2>{job.title}</h2><p>{job.place} · {job.area}</p><strong>{job.salary}</strong></div><button className="apply-button">View role ↗</button></article>)}</div></div></div> }
function AuthModal({ mode, role, setRole, close }: { mode: 'login' | 'register'; role: Role; setRole: (role: Role) => void; close: () => void }) { return <div className="modal-backdrop" onClick={close}><div className="auth-modal" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><span className="brand-mark large">F</span><p className="eyebrow">WELCOME TO FLOORSTAFF</p><h2>{mode === 'login' ? 'Welcome back.' : 'Find your place.'}</h2><p className="modal-copy">{mode === 'login' ? 'Sign in to see your local restaurant community.' : 'Choose how you want to take part in the hospitality community.'}</p>{mode === 'register' && <div className="role-options">{(['Customer', 'Employee', 'Manager'] as Role[]).map((item) => <button className={role === item ? 'selected' : ''} key={item} onClick={() => setRole(item)}><strong>{item}</strong><small>{item === 'Customer' ? 'Discover and give feedback' : item === 'Employee' ? 'Build your reputation' : 'Grow your restaurant'}</small></button>)}</div>}<label>Email<input type="email" placeholder="you@example.com" /></label><label>Password<input type="password" placeholder="••••••••" /></label>{mode === 'register' && <label>Your city<input type="text" defaultValue="Tbilisi" /></label>}<button className="primary-button full">{mode === 'login' ? 'Sign in' : `Create ${role.toLowerCase()} account`} <span>→</span></button><button className="modal-switch">{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button></div></div> }
export default App
